# Generated by Django 6.0.4 on 2026-05-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('store_location', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=50)),
                ('prev_cups', models.FloatField(default=0.0)),
                ('prev_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prediction_input',
            },
        ),
    ]
